# Generated by Django 5.1.5 on 2025-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_slm", "0008_software_release_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareproductversion",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
