# Generated by Django 5.1.5 on 2025-02-24 18:03

import netbox_slm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_slm", "0009_softwareproductversion_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarelicense",
            name="spdx_expression",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[netbox_slm.models.validate_spdx_expression],
            ),
        ),
    ]
