---
services:
  netbox:
    ports:
      - "8001:8080"
    build:
      context: ..
      dockerfile: ci/Dockerfile-CI
    image: netbox:slm
    environment:
      - COVERAGE_FILE=/tmp/.coverage
    healthcheck:
      disable: true
    volumes:
      - ./config:/etc/netbox/config:ro
      - ./reports:/ci/reports:rw
      - ../netbox_slm:/opt/netbox/netbox/netbox_slm:ro
  netbox-worker:
    image: netbox:slm
    depends_on:
      - netbox
    healthcheck:
      disable: true
  netbox-housekeeping:
    image: netbox:slm
    depends_on:
      - netbox
    healthcheck:
      disable: true
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
