version: '3.7'
services:
  netbox:
    ports:
      - "8001:8080"
    build:
      context: ..
      dockerfile: ci/Dockerfile-CI
    image: netbox:slm
    environment:
      - COVERAGE_FILE=/ci/.coverage
    volumes:
      - ./reports:/ci/reports
  netbox-worker:
    image: netbox:slm
  netbox-housekeeping:
    image: netbox:slm
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
