---
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Build the Docker image
      run: docker compose build --no-cache

    - name: Verify the Docker image
      # smoke test by checking if the migrations for app netbox_slm can be displayed
      run: docker compose run netbox sh -c "/opt/netbox/venv/bin/python manage.py showmigrations netbox_slm"

    - name: Run Django tests with coverage for netbox_slm
      run: |
        chmod go+w ci/reports
        docker compose run netbox sh -c "\
          /opt/netbox/venv/bin/coverage run --source='netbox_slm' manage.py test netbox_slm &&\
          /opt/netbox/venv/bin/coverage report --fail-under=0 &&\
          /opt/netbox/venv/bin/coverage xml -o /ci/reports/coverage.xml"
        sed -i "s/<source>\/opt\/netbox\/netbox<\/source>/<source><\/source>/" ci/reports/coverage.xml
      timeout-minutes: 6

    - name: Sonar scan
      if: env.SONAR_TOKEN != null
      uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
