---
name: Python

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.11
          - python-version: 3.12
          - python-version: 3.13
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ci tools
      run: pip install .[ci]

    - name: Run ruff lint
      run: ruff check netbox_slm

    - name: Run ruff format
      run: ruff format --check netbox_slm
