name: Python

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install tools
      run: pip install .[tools]

    - name: Run ruff lint
      run: ruff check netbox_slm

    - name: Run ruff format
      run: ruff format netbox_slm
